### ISSUE TITLE
HTML element `id`s need to be unique

### ISSUE THREAD

**Issue by jhfrench** [WhiteHouse/playbook#102]
There are two HTML elements in the playbook with an id of "plays":

`$('[id="plays"]') //[<a class=​"anchor_offset" id=​"plays">​</a>​, <div id=​"plays" class=​"outer_container">​…​</div>​]`

HTML [element `id`s need to be unique](http://www.w3.org/TR/html401/struct/global.html#h-7.5.2).

**Comment by jhfrench** [comment]
Confirmed that "plays" is the only duplicated id (using `$('[id]').each(function(){ console.log( $(this).prop('id') ); });` )

**Comment by cew821** [comment]
Good catch, thanks. Will try to update this soon.

**Comment by jhfrench** [comment]
Happy to help...
