### ISSUE TITLE
Printer-friendly version, please. 

### ISSUE THREAD

**Issue by elledmytryszyn** [WhiteHouse/playbook#156]
Not all content is worthy of printing -- but this information? -- very worthy! I really like the checklists & questions but they'd work better for me if I could have a printer friendly version. Small text is fine -- it doesn't have to take up a lot of pages; similiar to a quick reference card would be very handy to have, and to distribute to the team. Think you could make this happen?

**Comment by cew821** [comment]
Thanks for your feedback! Could you be more specific about what you would
like to be different about the printed version? We have attempted
to provided a print-friendly style that you will see if you print the file
from your browser, so I am curious what about that style you would like to
be different.

**Comment by cew821** [comment]
Closing for now, but please do feel free to provide some more specific feedback on what you would liketo be different about the print style.
