### ISSUE TITLE
Use HTTPS by default

### ISSUE THREAD

**Issue by csoghoian** [WhiteHouse/playbook#22]
Any new federal website should be using HTTPS by default. In 2014, there just isn't a good reason to not do so.

I realize that you are using github pages for playbook.cio.gov, and that github pages does not let you use a custom domain name with HTTPS (see https://konklone.com/post/github-pages-now-supports-https-so-use-it for more info). Until github fixes this, the right solution is for you to host your website elsewhere. Perhaps you could use Amazon Cloudfront+S3, which supports HTTPS for free, and allows custom domains.

HTTPS by default is the right thing to do, and you should be setting a good example for other agencies. Plus, it will help your Google pagerank (see: http://googleonlinesecurity.blogspot.com/2014/08/https-as-ranking-signal_6.html)

**Comment by cben** [comment]
FYI, even if Cloudflare allowed Full Strict, there would remain an insecure link.
Github support has explained:

> While HTTPS requests may appear to work, our CDN provider is adding and removing the encryption at their end, and then the request is transmitted over the open internet from our CDN provider to our GitHub Pages infrastructure, creating the appearance of trustability.

-- full text in [comment on Eric's post](https://konklone.com/post/github-pages-now-supports-https-so-use-it#comment-54d648a969702d6be8110a00)

As long as that is true, there is no way to secure Github Pages.
Doesn't change your reasoning for a static site, but worth knowing.

**Comment by konklone** [comment]
> As long as that is true, there is no way to secure Github Pages.
> Doesn't change your reasoning for a static site, but worth knowing.

Correct on both counts. FWIW, the site doesn't use CloudFlare, but rather an in-house proxy, configured by @PaulSD. That doesn't solve the problem of the link between Fast.ly and GitHub, which is something out of our control. I think the team here's done the best they can under the circumstances, and aren't running a website that's likely to put people at risk (unlike the MayOne.us example I linked above, the discussion of which has sadly been taken offline).
