### ISSUE TITLE
Add anchors to playbook headings

### ISSUE THREAD

**Issue by pburtchaell** [WhiteHouse/playbook#43]
I'd like to propose that you wrap each of the headings in an anchor:

```
<a href=#play1>
  <h1>Play 1 Title</h1>
</a>
```

This would allow one to click on the title of the heading and get a URL like [http://playbook.cio.gov/#play1](http://playbook.cio.gov/#play1). If you want to share a particular section of the playbook with someone, having the section's id in the URL is helpful.

See the [Bower documentation](http://bower.io/#install-bower) for an example of this functionality.

**Comment by cew821** [comment]
This is fixed by #57 and deployed!
