### ISSUE TITLE
Advice for incident response, accident reporting, & post-mortems?

### ISSUE THREAD

**Issue by mstone** [WhiteHouse/playbook#55]
Despite the best efforts of thousands of people, all sorts of things go wrong with the design and delivery of large-scale digital services. Therefore, what advice should we give to playbook readers about how to prepare, respond, & learn from things going wrong with their digital services?

**Comment by jallspaw** [comment]
FYI, it took roughly two years to followup on my above comment, but we have just published what I referred to as _"suggestions and thoughts on what an evolved 'Learning Review'"_ in the form of a generalized Debriefing Facilitation Guide. 

It is located [here](https://github.com/etsy/DebriefingFacilitationGuide) (in both markdown and PDF) and we hope it can serve as a reference for the field on this topic. I'd like to suggest that the USDS and like-focused groups within the government could consider using this approach. 

FWIW, there is more background [here](https://codeascraft.com/2016/11/17/debriefing-facilitation-guide/).

@mdickers47 @pahlkadot @jezhumble @haleyvandyck
