### ISSUE TITLE
Branding -- iconography and formats for printing 

### ISSUE THREAD

**Issue by michael-b-martin94** [WhiteHouse/playbook#63]
I am an engineer, not a marketer, and like others, I get infuriated by marketing types getting in the way of good technical product, but I have learned the value of branding in establishing ideas and products.  This effort will have to penetrate the diverse and labyrinthine cultures of the government, and building good messaging and branding will help.  

To build momentum for a cultural shift to embrace the principles in the playbook, you need to develop a connected iconography to represent the Digital Services group, the playbook, the techFAR, and related materials as they are produced.  The process of developing iconography can itself be opened up with a public call to artists and a comment process on leading contenders for icons, symbols, and publication templates.  One of my earliest lessons in designing software was that visual design counts for a lot.

A slogan could also be useful, though another hackneyed attempt at an inspirational phrase to drive the workforce could backfire. 

You also need to publish printable posters and flyers for people to post.  People need to be able to "fly the flag," and show that they are on board, and also have an easy way to communicate these ideas to others in their organizations.  Initial offerings could be simple pdfs of the list of plays in the playbook in letter-size, tabloid-size, and a size suitable for a large-format printer.  The larger format might be able to fit the checklists in.  If this effort is to turn into a cultural movement in government, people have to be able to identify themselves as part of the culture.

**Comment by cew821** [comment]
![usds_logo](https://cloud.githubusercontent.com/assets/1237498/5829027/f36dddba-a0d9-11e4-898d-bda66dc96353.png)

Ta-da!

Learn more about the U.S. Digital Service at www.whitehouse.gov/us-digital-service

This is closed as of #101
