### ISSUE TITLE
Make attribution more obvious on playbook page?

### ISSUE THREAD

**Issue by lukefretwell** [WhiteHouse/playbook#73]
When I first saw the playbook when it was announced, it was obvious that it came out of the White House, but that's because I read the blog post.

Today, when I went to it, it dawned on me that someone coming into it blindly may now know this is an official government work. It struck me that there was no context. Perhaps a logo in the header/footer or referential USDGS text would help.

Related discussion: https://twitter.com/mollieruskin/status/519583622706130944

**Comment by cew821** [comment]
We've added a link back to the U.S. Digital Service website, as of #101. Thanks for this idea!
