### ISSUE TITLE
Problem downloading docx version of TechFAR Handbook

### ISSUE THREAD

**Issue by bronx72** [WhiteHouse/playbook#76]
Using ".docx document" link on https://playbook.cio.gov/techfar/: 

https://playbook.cio.gov/assets/TechFAR%20Handbook_2014-08-07.docx
WARNING -- Access to this file is blocked by security measures for the following reason:
* File type attempted to download not allowed.
If you feel you have reached this message in error, you may contact the Service Desk at 5-4357 or the Network Operations Center at 5-7370.
File name: TechFAR Handbook_2014-08-07.docx

Don't need the document, just passing it along.

**Comment by cew821** [comment]
This is fixed as of #101.
